/* 
This file contains HTTP requests to the Todo API, either locally or remotely.
Use the REST Client extension for Visual Studio Code to send these requests.
Before sending, use the REST Client's environment picker to select either 'local' or 'remote', which sets the value of {{baseUrl}} for the requests.
For first-time use, you must enter 'local' or 'remote' into VS Code's input box. After that, you can select them.
For VS Code, you can set the environment variables in .vscode/settings.json.
(Use of a file .httpclient.env.json didn't work.)
*/

# ===== ROOT ENDPOINTS =====

### Get API Base Information (Root Endpoint)
GET {{baseUrl}}/
Accept: application/json

### Access Swagger UI
GET {{baseUrl}}/swagger-ui/index.html

### Try to call an invalid endpoint (Expect error)
GET {{baseUrl}}/todowrongendpoint
Accept: application/json

# ===== TODO ENDPOINTS =====

### Get all todos
GET {{baseUrl}}/todos
Accept: application/json

### Get an existing todo (first todo)
GET {{baseUrl}}/todos/0
Accept: application/json

### Get a non-existent todo (Expect error)
GET {{baseUrl}}/todos/99
Accept: application/json

### Get a todo with a wrong Accept header (Expect error)
GET {{baseUrl}}/todos/3
Accept: text/plain

### Add a new valid todo
POST {{baseUrl}}/todos
Content-Type: application/json

{
  "todo": "Test todo 3"
}

### Try to add an empty todo string (Expect error)
POST {{baseUrl}}/todos
Content-Type: application/json

{
  "todo": ""
}

### Try to add a null todo (Expect error)
POST {{baseUrl}}/todos
Content-Type: application/json

{
  "todo": null
}

### Try to add a todo with a too-short description (minimum 5 characters required) (Expect error)
POST {{baseUrl}}/todos
Content-Type: application/json

{
  "todo": "hi"
}

### Delete a todo
DELETE {{baseUrl}}/todos/2

### Try to delete a non-existent todo (Expect error)
DELETE {{baseUrl}}/todos/99

### Try to delete a todo with an incorrect parameter type (Expect error)
DELETE {{baseUrl}}/todos/three
