/* 
This file contains HTTP requests to the TODO API locally or remotely.
Use the REST Client extension for Visual Studio Code to send these requests.
Before sending, use the REST Client's environment picker to select either 'local' or 'remote', which will set the value of {{baseUrl}} for the requests. (For first time use, you must enter 'local' or 'remote' into vs studios input box. After that, you can select them.)
For VS Code you can set the environment variables in .vscode/settings.json.
(Use of a file .httpclient.env.json didn't work.):
*/

### Get all todos
GET {{baseUrl}}/todos
Accept: application/json

### Try to call wrong endpoint (Expect error)
GET {{baseUrl}}/todowrongendpoint
Accept: application/json


### Run swagger ui
GET {{baseUrl}}/swagger-ui/index.html

### Get an existing todo
GET {{baseUrl}}/todos/0
Accept: application/json

### Call a not existing todo (Expect error)
GET {{baseUrl}}/todos/99
Accept: application/json

### Call a with wrong accept header (plain text) (Expect error)
GET {{baseUrl}}/todos/3
Accept: text/plain

### Add a new valid todo
POST {{baseUrl}}/todos
Content-Type: application/json

{
  "todo": "Test todo 3"
}

### Try to add an empty todo (Expect error)
POST {{baseUrl}}/todos
Content-Type: application/json

{
  "todo": ""
}

### Try to add a todo with too short description (Expect error)
POST {{baseUrl}}/todos
Content-Type: application/json

{
  "todo": "hi"
}

### Delete a todo
DELETE {{baseUrl}}/todos/2

### Try to delete a not existing todo (Expect error)
DELETE {{baseUrl}}/todos/99

### Try to delete a todo with wrong parameter type (Expect error)
DELETE {{baseUrl}}/todos/three
