/* 
This file contains http requests to the todo api.
It is used to test the api.

To run a request, open the file in VS Code and use the according "Send Request" button.
*/

### You can switch between localhost or the published URL by commenting/uncommenting one of these:
@baseUrl = http://localhost:8080
# @baseUrl = https://todo-rest-api-spring-boot3.onrender.com

### Get all todos
GET {{baseUrl}}/todos
Accept: application/json


### Run swagger ui
GET {{baseUrl}}/swagger-ui/index.html

### Get a specific todo
GET {{baseUrl}}/todos/3
Accept: text/plain


### Add a new valid todo
POST {{baseUrl}}/todos
Content-Type: application/json

{
  "todo": "Test todo 3"
}

### Add an empty todo (Expect error)
POST {{baseUrl}}/todos
Content-Type: application/json

{
  "todo": ""
}

### Add a todo with too short description (Expect error)
POST {{baseUrl}}/todos
Content-Type: application/json

{
  "todo": "hi"
}

### Delete a todo
DELETE {{baseUrl}}/todos/3
