### Get all todos
GET http://localhost:8080/todos
Accept: application/json

### Get a specific todo
GET http://localhost:8080/todos/0
Accept: text/plain

### Add a new valid todo
POST http://localhost:8080/todos
Content-Type: application/json

{
  "todo": "Test todo 3"
}

### Add an empty todo (Expect error)
POST http://localhost:8080/todos
Content-Type: application/json

{
  "todo": ""
}

### Add a todo with too short description (Expect error)
POST http://localhost:8080/todos
Content-Type: application/json

{
  "todo": "hi"
}

### Delete a todo
DELETE http://localhost:8080/todos/3